//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsyncSQLOperations.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int Port {
            get {
                return ((int)(this["Port"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mail.russianpost.ru")]
        public string Host {
            get {
                return ((string)(this["Host"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Template {
            get {
                return ((string)(this["Template"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ReplicaImport")]
        public string ImportReplicaProc {
            get {
                return ((string)(this["ImportReplicaProc"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ReplicaExport")]
        public string ExportReplicaProc {
            get {
                return ((string)(this["ExportReplicaProc"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Configs\\ConnectStageList.xml")]
        public string StageListPath {
            get {
                return ((string)(this["StageListPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Configs\\ConnectConfig.xml")]
        public string ConfigPath {
            get {
                return ((string)(this["ConfigPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int ThreadCount {
            get {
                return ((int)(this["ThreadCount"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dmitry.sushevsky@norbit.ru")]
        public string MailRecep {
            get {
                return ((string)(this["MailRecep"]));
            }
            set {
                this["MailRecep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dmitry.sushevsky@norbit.ru")]
        public string MailCCRevep {
            get {
                return ((string)(this["MailCCRevep"]));
            }
            set {
                this["MailCCRevep"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dmitry.sushevsky@norbit.ru")]
        public string SenderMail {
            get {
                return ((string)(this["SenderMail"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("144011,144001,143988,143987,143986,143985,143983,143968,143960,143930,143920,1439" +
            "14,143912,143906,143902,143825,143800,143722,143720,143716,143712,143650,143632," +
            "143627,143615,143611,143591,143560,143541,143522,143517,143513,143502,143440,143" +
            "411,143395,143380,143370,143360,143354,143336,143335,143325,143322,143321,143320" +
            ",143316,143304,143301,143240,143217,143212,143210,143126,143118,143085,143078,14" +
            "2963,142955,142953,142944,142943,142931,142930,142927,142924,142917,142908,14290" +
            "2,142860,142855,142840,142817,142813,142802,142715,142700,142504,142450,142439,1" +
            "42408,142303,142302,142275,142263,142215,142155,142116,142113,142101,142073,1420" +
            "64,142062,142052,142040,142034,142033,142032,142006,142001,141982,141980,141932," +
            "141916,141894,141892,141850,141832,141830,141829,141822,141704,141656,141644,141" +
            "642,141640,141632,141621,141613,141605,141580,141570,141560,141555,141551,141542" +
            ",141540,141533,141508,141503,141441,141426,141425,141370,141362,141336,141330,14" +
            "1327,141326,141323,141305,141303,141284,141271,141241,141220,141217,141216,14121" +
            "4,141204,141201,141150,141144,141143,141107,141102,141091,141078,141075,141073,1" +
            "41070,141055,141054,141018,141004,140761,140752,140635,140633,140621,140620,1406" +
            "12,140574,140570,140542,140531,140530,140512,140492,140491,140483,140482,140479," +
            "140476,140473,140471,140451,140450,140422,140413,140404,140342,140341,140317,140" +
            "306,140187,140186,140182,140160,140155,140152,140125,140124,140121,140120,140093" +
            ",140082,140074,140032,140000,108850,108841,108828,108823,108822,108821,108820,10" +
            "8815,108814,108810,108808,108805,108804,108803,108801")]
        public string OPSFilter {
            get {
                return ((string)(this["OPSFilter"]));
            }
        }
    }
}
